#!/bin/bash
set -e
repoDir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
python3 "${repoDir}/code/update.py" "${repoDir}/archives/" 2> >(tee "${repoDir}/archives/update.log" >&2)
pushd "${repoDir}"
git add .
git commit -m "Automatic commit by run"
git push
